### ISSUE TITLE
pipelineloader

### ISSUE THREAD

**Issue by dieloz** [ins-amu/ddmisp#2]
Hi Viktor,
Where can I find pipelineloader package? I can't find this in your repository
Thanks beforehand,
Diego

**Comment by sipv** [comment]
Hi, you are right, pipelineloader is not published. Basically, all it does is load the processed subject data (structural connectome, SEEG, parcellation). These data are not publicly available (as they contain identifiable patient data) and in a custom, non-standardized data structure, so publishing pipelineloader on its own did not make much sense. I admit this can pose bit of a challenge in reusing the code and I wanted to make some mockup data set to make it easier, but did not manage to do that yet.

Perhaps if you describe your use case / data available I could guide you better in adapting the code, or at least clear things up in the documentation. Feel free to contact me privately on email if needed.

**Comment by dieloz** [comment]
Hi Viktor
Thanks for your prompt reply. I understand the issue and I'll write down my own function and I'll used public data to run your code.
Best
Diego

**Comment by sipv** [comment]
Good luck, and don't hesitate to ask if something is unclear!
